### ISSUE TITLE
Machines endpoint and list

### ISSUE THREAD

**Issue by Emiel-Codebridge** [PokeAPI/pokedex-promise-v2#23]
Can't seem to find where you put [Machines endpoint](https://pokeapi.co/docsv2/#machines-section) in the API. Is it missing or can i find it in another endpoint?

**Comment by Naramsim** [comment]
Hi @Emiel-Codebridge, you are looking for the only endpoint we haven't mapped 😄. 
I pushed a [branch](https://github.com/PokeAPI/pokedex-promise-v2/tree/machines) that adds these endpoints (/machine/ and /machine/id/). Let's wait @TheTommyTwitch review.

However, to query machines, I use this call: https://pokeapi.co/api/v2/item/tm01/, because /machine/id/ endpoint, basically, redirects you to this URL.
