### ISSUE TITLE
error in typescript generator

### ISSUE THREAD

**Issue by Joaovitorsw** [PokeAPI/pokedex-promise-v2#55]
![image](https://user-images.githubusercontent.com/86388366/146335230-7ae7ed7f-b3cd-4e2c-ab44-87e653e1a80e.png)
the project gave an error in the build due to a small detail it is generating only the last non-standard files and causes the build error, making a local change it is already able to build again
![image](https://user-images.githubusercontent.com/86388366/146335543-057d85f7-16ad-4504-abc3-ca70c7f49657.png)

**Comment by Naramsim** [comment]
Can you list all the steps you have taken to reach this output? The commands?

Did you use this (https://github.com/PokeAPI/pokedex-promise-v2#development) as a reference?

**Comment by C-Garza** [comment]
Yeah I see the same issue actually when using `npm` to install the package. The type file doesn't have any reference to `ListEndpointOptions` because the `src` folder which includes that interface isn't in the `dist/src` folder. 

I see that `ListEndpointOptions` does have a type included in the typings file though, so perhaps the `Main.ts` file should be modified to reference that one. I think modifying the `methodStructure` object on lines [268 and 317](https://github.com/PokeAPI/pokedex-promise-v2/blob/4f533c81253e30366d339f56ea75500b370fbeb2/generator/Main.ts#L268-L355) to replace `type: 'ListEndpointOptions'` after it's included in the `generatedMethod` to have it be `PokeAPI.ListEndpointOptions` and then regenerating the `index.d.ts` file should fix it. Something like:
```js
methodStructure.parameters[0].type = "PokeAPI.ListEndpointOptions";
```

**Comment by HRKings** [comment]
Hey, thanks for pointing this out! The problem is on [line 74 of the TypesGenerator](https://github.com/PokeAPI/pokedex-promise-v2/blob/4f533c81253e30366d339f56ea75500b370fbeb2/generator/TypesGenerator.ts#L74), it should be `rootModule` and not `namespace`, changing this should correct the issue and the structure in general
